### ISSUE TITLE
Issue_1

### ISSUE THREAD

**Issue by Github0045** [ElzeroWebSchool/Issue_Tracking#1]
![img](https://user-images.githubusercontent.com/85316026/177189330-882dfe46-a173-4b76-81e7-11816612067d.png)
.السلام عليكم, انا اكيد المشكلة دي مش فارقة معايا بس قولت انها ممكن تكون فارقة معاك

**Comment by ElzeroWebSchool** [comment]
تسلم ربنا يبارك فيك عدلتها <3
