### ISSUE TITLE
مدة الكورس

### ISSUE THREAD

**Issue by devahmedabdo** [ElzeroWebSchool/Issue_Tracking#10]
ممكن يا باشمهندس ان شاء الله تزود حاجه في الكورسات الجديده ودي لان مفيش كورس في العالم طبعا هيلم كل المواضيع 
لكن ممكن نتغلب علي الموضوع دا او نحسنه عن طريق 
انك اخر كل فيديو ممكن تقول الحاجات اللي حضرتك ما قولتهاش او تكتبها علي الموقع مثلا 
فيدو ال array تكتب ابحث عن ال find , filter ,  وهكذا بحيث نقلل وقت انى ابحث عن الحاجات اللي مش عارف هي موجوده ولا لا و فنفس الوقت يبقي قولت كل حاجه عن الموضوع دا 
وربنا يجزيك خير عننا ويجعله في ميزان حسناتك

**Comment by ElzeroWebSchool** [comment]
ربنا يبارك فيك ويكرمك دة فعلا موجود في خطة الدراسة 
لو فتحت اي خطة دراسة هتلاقي في نهايتها تبحث عن ايه علشان تكمل معلوماتك 
وكمان في كتير فيديوهات في الكورس بكون كاتب حاجات تبحث عنها 
شوف هنا
https://elzero.org/study/php-bootcamp-2022-study-plan/

![2022-07-11_20-32-36](https://user-images.githubusercontent.com/2456832/178334488-66cf2169-8084-4d1e-b37b-d6f31c8111a8.png)
