### ISSUE TITLE
php-bootcamp-assignments-Week06-Q06

### ISSUE THREAD

**Issue by MekadAlibrahem** [ElzeroWebSchool/Issue_Tracking#11]
يوجد خطأ  بسيط في التكليف السادس الاسبوع السادس 
 "العمليات الحسابية هي الجمع والطرح و (القسمة) " مطلوب القسمة هنا  و بالمثال مستخدم عملية الضرب وليس القسمة  
وبعدها محدد العمليات " العمليات الحسابية المتاحة هي add, subtract, multiply"

**Comment by ElzeroWebSchool** [comment]
أحسنت بارك الله فيك تم إضافة كلمة الضرب بدل القسمة شكرا لك
