### ISSUE TITLE
Bug on the JavaScript Study Plan

### ISSUE THREAD

**Issue by fareskhalid** [ElzeroWebSchool/Issue_Tracking#14]
On the right panel (the weeks indicator) there is a bug, week number doesn't highlighted when i reach the week title (scrolling until title).
![Screenshot from elzero or](https://user-images.githubusercontent.com/55852368/179284194-2d323ddf-163c-4d91-870e-c2424cd84b2d.png)

**Comment by PhilopaterHany** [comment]
انزل تحت كام بكسل بس هتتحل عادي

**Comment by ElzeroWebSchool** [comment]
انا جربتها مفيش المشكلة دي خالص
