### ISSUE TITLE
Python Course | From 103 To 116 | Assignment 6

### ISSUE THREAD

**Issue by PhilopaterHany** [ElzeroWebSchool/Issue_Tracking#15]
تكليفات الدروس من 103 الي 116
التكليف السادس
لينك التكليف: https://elzero.org/python-assignments-lesson-from-103-to-116/
مكتوب في الكلام ال فوق اننا نعمل class اسمو  name و مكتوب في الكود تحت نعمل كلاس اسمو Text

![image](https://user-images.githubusercontent.com/86812518/179533480-85a81a9d-c068-4048-8876-6b639ee836e4.png)

**Comment by ElzeroWebSchool** [comment]
تم عمل اللازم بارك الله فيك
