### ISSUE TITLE
PHP Bootcamp - pagination between lessons

### ISSUE THREAD

**Issue by Zold1** [ElzeroWebSchool/Issue_Tracking#18]
* Python course has a pagination between lessons

![Python](https://user-images.githubusercontent.com/97743566/182049731-788f11c0-8050-4fb9-b14b-633ae02e8dd6.png)

* PHP not!

![PHP](https://user-images.githubusercontent.com/97743566/182049743-4713c803-312f-4572-98f1-2569accb30bb.png)

**Comment by ElzeroWebSchool** [comment]
Thanks so much Done
