### ISSUE TITLE
Question answer page

### ISSUE THREAD

**Issue by alieldeba** [ElzeroWebSchool/Issue_Tracking#19]
يا باشمهندس ياريت تعديل السن من 16 الى 15 لأن قرار استخراج البطاقة اتغير :)

![Screenshot (182)](https://user-images.githubusercontent.com/88302640/182483874-84b16388-4d41-4f51-8801-b59e95a22753.png)

**Comment by ElzeroWebSchool** [comment]
تم بارك الله فيك
