### ISSUE TITLE
interview questions playlist

### ISSUE THREAD

**Issue by alieldeba** [ElzeroWebSchool/Issue_Tracking#21]
## عندى اقتراحين ياباشمهندس

> حضرتك ممكن تعمل playlist تكون لل interview questions فى القناة لأن اى حد بيجهز نفسه للتوظيف بيدور على الحاجات دى
---
> حضرتك ممكن تعمل repo جديدة للأقتراحات زى دى كدا بلظبط بس علشان الريبو دى ميكونش فيها لغبطه بين ال issue الخطأ و ال issue الاقتراح او حتى ال issue السؤال او حتى حضرتك ممكن تعدل فى اعدادات ال issue و تخلى الناس تقدر تعمل tag لل issue على انه اقتراح او خطأ هكذا ...

**Comment by ElzeroWebSchool** [comment]
عادي مفيش مشكلة خلي الاقتراحات هنا برضة نشتغل عليها 
بالنسبة للقائمة موجودة بالفعل فيها حاليا بعض المسائل السهلة هنزود عليها شوية مسائل من اللي بتيجي في الانترفيو مع شرحها باذن الله
