### ISSUE TITLE
Typescript Study Plan

### ISSUE THREAD

**Issue by PhilopaterHany** [ElzeroWebSchool/Issue_Tracking#23]
الاسبوع الثالث غير موجود

![image](https://user-images.githubusercontent.com/86812518/184041737-5cc874a4-1797-405f-ae29-978a3567ed80.png)

**Comment by alieldeba** [comment]
اه فعلا انا حاسس ان زى ما يكون فى جلتش فى الصفحة او حاجة غلط مخلية الاسبوع الثالث ميظهرش

**Comment by ElzeroWebSchool** [comment]
تم التعديل شكرا لك
