### ISSUE TITLE
Php Bootcamp week09 Assignment 06

### ISSUE THREAD

**Issue by MekadAlibrahem** [ElzeroWebSchool/Issue_Tracking#25]
مرحبا 
ممكن وجود خطأ في تكليفات الاسبوع 9  التكليف السادس 
المطلوب تنقية الروابط لتكون صحيحة و سليمة وبالتالي الخرج بعد تنقية الروابط يجب ان يكون  valid  
الخرد في التكليف هو not valid 

![image](https://user-images.githubusercontent.com/79482795/184434948-852e1e38-140d-4bab-9100-c6f9e07791be.png)

**Comment by ElzeroWebSchool** [comment]
تم التعديل شكرا لك
