### ISSUE TITLE
Website logo enhancement

### ISSUE THREAD

**Issue by justanonymoushuman** [ElzeroWebSchool/Issue_Tracking#26]
<div style='direction: rtl; text-align: right;'>

<h1 align='center'>شعار الموقع</h1>

شكرًا شكرًا شكرًا شكرًا لك بشمهندس أسامة على كل شيء تُقدمه لنا، ربنا يكرمك ويجعله في ميزان حسناتك 💜.
هذا شيء بسيط جدًا جدًا لك، ولا أحسبه حتى شُكر؛ لأن الشكر قليل في حقك، دائمًا ما أدعوا لك بأن يُكرمك الله في الدنيا والآخرة 💜.

وهذا الشيء البسيط هو تطوير لموقع الأكاديمية؛ لاحظت أن شعار الموقع ليس بصيغة SVG، وجودته سيئة، أعلم أنه ليس لديك وقت لهكذا أمور، أعانك االه ووفقك، لهذا أعدت تصميمه مع المحافظة على الأيقونة نفسها، ولكن التغيير في نوع الخط وكيفية عرضه، وأيضًا جعل هذا الشعار بصيغة SVG، وجودة عالية.

لتحميل الشعار [من هنا](https://github.com/justanonymoushuman/shared-files/blob/main/images/logo.svg).

هذه النتيجة، قبل وبعد!

<img src='https://raw.githubusercontent.com/justanonymoushuman/shared-files/main/images/logo-before-after.png' style='display: block; text-align: center;'/>

<br>
<br>

بعد تجربته على الموقع، لاحظت أن إضافة هذه التنسيقات البسيطة تجعله مُناسب أكثر ومُريح للعين:

<img src='https://raw.githubusercontent.com/justanonymoushuman/shared-files/main/images/css.png' style='display: block; text-align: center;'/>

</div>

**Comment by ElzeroWebSchool** [comment]
ربنا يكرمك ويبارك فيك حاليا بغير البراند كله والحمد لله شكرا على تعبك جدا <3
