### ISSUE TITLE
Enhance the icons of the courses page

### ISSUE THREAD

**Issue by justanonymoushuman** [ElzeroWebSchool/Issue_Tracking#27]
<div style='direction: rtl; text-align: right;'>

<h1 align='center'>أيقونات الدورات التعليمية</h1>

لاحظت أن أيقونات الدورات التعليمية جزء منها SVG وجزء آخر PNG، وكنوع من الدعم والشكر البسيط جدًا لك والذي أبدًا لا يوفيك حقك 💜، خصصت جزء من وقتي للبحث عن أيقونات مناسبة وتكون بصيغة SVG؛ لأنها أكثر وضوحًا وأفضل بكثير!

جميع الـ SVGs موجودة في الملف المضغوط ([من هنا](https://github.com/justanonymoushuman/shared-files/tree/main/files))، وأيضًا أيقونات لتقنيات أخرى لدورات إن شاء الله في المستقبل لربما ستشرحها، مثل Vue, React, Webpack، وغيرها!

هذا أيضًا رابط موقع فيه الشعارات الأصلية لكل التقنيات واللغات في عالم البرمجة بصيغة SVG، الرابط [من هنا](https://devicon.dev/).

هذه النتيجة، قبل وبعد!

<img src='https://raw.githubusercontent.com/justanonymoushuman/shared-files/main/images/courses-before-after.png' style='display: block; text-align: center;'/>

</div>

**Comment by ElzeroWebSchool** [comment]
عظيم جدا بارك الله فيك بغيرهم اليوم باذن الله شكرا لك <3
