### ISSUE TITLE
Frontend Challenges | Inverted previous and next buttons

### ISSUE THREAD

**Issue by mouatezbenariba** [ElzeroWebSchool/Issue_Tracking#28]
من المفروض عند الضغط على "السابق" يأخذك الموقع على التحدي السابق ونفس الأمر بالنسبة عن الضغط على (التالي). ولكن هنا يجب أن تكون كلمة السابق والتالي معكوستان.

**Comment by ElzeroWebSchool** [comment]
انا جربتها حاليا ومظبوطة مفيهاش اي مشكلة 
ممكن طريقة عرض التحديات بالانجليزي هي اللي مسببة المشكلة 
كدة ظبطها وخليت آخر تحدي هيظهر اول واحد فوق على اليمين وكدة بقت منطقية 
تسلم
