### ISSUE TITLE
PHP Bootcamp | YouTube Icon & Button

### ISSUE THREAD

**Issue by PhilopaterHany** [ElzeroWebSchool/Issue_Tracking#3]
ايكون اليوتيوب البيفتح لينك الدرس علي اليوتيوب **مش موجود** علي كل الدروس من بعد رقم 19
و كذلك الbutton بتاع شاهد علي اليوتيوب نفس المشكلة و في نفس الدروس

![image](https://user-images.githubusercontent.com/86812518/177263176-4c3633ba-cde3-4611-b5de-b94952d48d9c.png)
![image](https://user-images.githubusercontent.com/86812518/177266379-36a32f5f-d014-4ac0-9c5f-947dbbf87da7.png)

**Comment by ElzeroWebSchool** [comment]
كله تمام حاليا لحد الدروس اللي نزلت 
ربنا يكرمك
