### ISSUE TITLE
Wrong Value In JavaScript (2015), Lesson (20), Second Example, Line 9

### ISSUE THREAD

**Issue by George-Nabil-Aziz** [ElzeroWebSchool/Issue_Tracking#30]
In Line 9 the Value of [ console.log(myName); ] will be Osama not Ahmed
because the previous declaration of myName in Line 2 is Osama

![Typo ](https://user-images.githubusercontent.com/106881454/208291990-d6f9fb4f-6870-41d8-bd1b-e59093e1fcab.jpg)

**Comment by ElzeroWebSchool** [comment]
Thanks So Much Done
