### ISSUE TITLE
خطأ في كلمة طباعة

### ISSUE THREAD

**Issue by Kha-Led-98** [ElzeroWebSchool/Issue_Tracking#31]
![image](https://user-images.githubusercontent.com/85019681/210154846-70ad61fc-3726-40ab-b8ca-a78aac9938fd.png)

يجب عليك إستعمال جميع المتغيرات في سطر  => "بطاعة"  النتيجة

**Comment by alieldeba** [comment]
ابعت لو سمحت ال url بتاع الصفحة علشان الزيرو يقدر يعرف الخطأ موجود فى انهو صفحة @Kha-Led-98

**Comment by ElzeroWebSchool** [comment]
بارك الله فيك تم التصليح
