### ISSUE TITLE
PHP Bootcamp assignment02 week011 

### ISSUE THREAD

**Issue by MekadAlibrahem** [ElzeroWebSchool/Issue_Tracking#33]
في التكليف الثاني مطلوب إضافة 15 ساعة و 15 دقيقة و 15 ثانية ولكن خرج الكود المكتوب  "15:15:10" يفترض يكون   "15:15:15"

**Comment by alieldeba** [comment]
ابعت اللينك لو سمحت بتاع الصفحة

**Comment by MekadAlibrahem** [comment]
https://elzero.org/php-bootcamp-assignments-lesson-from-92-to-97/
 
التكليف رقم ٢

**Comment by ElzeroWebSchool** [comment]
تم التصليح شكرا لك
