### ISSUE TITLE
ads on site

### ISSUE THREAD

**Issue by AmgadEisa** [ElzeroWebSchool/Issue_Tracking#37]
السلام عليكم 
برجاء ملاحظة أن الإعلانات الموجودة بالموقع وعلى قناة اليوتيوب بدأ يظهر فيها الكثير من الصور الفاضحة وأذكركم بقول رسول الله صلى الله عليه وسلم "( إنك لن تدع شيئاً لله عز وجل إلا بدلك الله به ما هو خير لك منه ) رواه أحمد ( 21996) .

**Comment by ElzeroWebSchool** [comment]
عليكم السلام اي اعلان فيه مشكلة ابعتلي اللينك الخاص بيه على ميل القناه وبنعمله فلتر باذن الله <3
