### ISSUE TITLE
PHP Bootcamp | Arrow Navigation & YouTube Button

### ISSUE THREAD

**Issue by PhilopaterHany** [ElzeroWebSchool/Issue_Tracking#4]
الأسهم البنتنقل بيها بين الدروس  **مش موجودين** 

![image](https://user-images.githubusercontent.com/86812518/177265678-82c3498e-05cf-46d2-8877-0135fe231346.png)

مع العلم انهم **موجودين** عادي في باقي الكورسات زي ال JavaScript Bootcamp مثلا

![image](https://user-images.githubusercontent.com/86812518/177265521-0cf56bdd-358e-4a8c-ad5e-ed6174c59c71.png)

يا ريت برضو الbutton بتاع شاهد علي اليوتيوب يبقا موحد في كل الكورسات يعني يبقا نقس اللون و نفس الكلام المكتوب جواه عشان انا ملاحظ ان بينهم فروق بسيطة

---

برضو في كورس الphp اسم كل درس البيبقا فوق مش مكتوب جمبو رقم الدرس علي عكس باقي الكورسات

![image](https://user-images.githubusercontent.com/86812518/177268912-58aebb51-7395-401a-80b3-7194ac47a86d.png)
![image](https://user-images.githubusercontent.com/86812518/177268751-87d83332-7f42-45af-b4f2-3841d22b8c1b.png)

**Comment by ElzeroWebSchool** [comment]
ربنا يكرمك حاليا الصفحة موحدة ومفيهاش مشاكل والحمد لله
