### ISSUE TITLE
a typo in "tutorials-centering-elements-horizontally-and-vertically"

### ISSUE THREAD

**Issue by mido-dev1** [ElzeroWebSchool/Issue_Tracking#40]
![Screenshot from 2023-08-02 19-17-58](https://github.com/ElzeroWebSchool/Issue_Tracking/assets/123629444/85b6f7f3-23f9-4e13-a935-8eed8d03d087)

Here instead of "/* Margin + Transform */" 
It should look like this "/* Position + Transform */"

Link : [https://elzero.org/tutorials-centering-elements-horizontally-and-vertically/](https://elzero.org/tutorials-centering-elements-horizontally-and-vertically/)

**Comment by ElzeroWebSchool** [comment]
Thanks Done
