### ISSUE TITLE
اضافة كورس Ruby On Rails

### ISSUE THREAD

**Issue by Abo5** [ElzeroWebSchool/Issue_Tracking#43]
اتمنى اضافة كورس جديد وهو عن لغة Ruby والعمل على اطار عمل ROR (Ruby On Rails) 

واتمنى لكم دوام التوفيق والنجاح
عبدالله.

**Comment by ElzeroWebSchool** [comment]
الله يباركلك الجدول حاليا مليان الكورسات اللي شغال عليها زي اساسيات البرمجة 
ان شاء الله لو توفر الوقت نعمل كورس
