### ISSUE TITLE
096 - CSS Styling And Stylesheets

### ISSUE THREAD

**Issue by abderahmenabdou** [ElzeroWebSchool/Issue_Tracking#44]
الأكواد الموجودة في درس 095 - ClassList Object and Methods هي نفسها الموجودة في 096 - CSS Styling And Stylesheets
https://elzero.org/javascript-2021-classlist-object-and-methods/
https://elzero.org/javascript-2021-css-styling-and-stylesheets/

**Comment by ElzeroWebSchool** [comment]
تمت شكرا لك
