### ISSUE TITLE
الموقع كان معلق 

### ISSUE THREAD

**Issue by MohamedWagdyB** [ElzeroWebSchool/Issue_Tracking#45]
السلام عليكم بشمهندس اسامه كنت بحاول اخش علي الموقع الضهر مكنش بيخش كنت بحسب المشكله من عندي بس هوا حاليا شغال تمام

**Comment by ElzeroWebSchool** [comment]
عليكم السلام ياريت بارك الله فيك ترفق صورة من اللي بيظهر لك لو وقف مرة اخرى علشان اقدر اعرف المشكلة
