### ISSUE TITLE
كود الفيديو رقم 96 في ال js

### ISSUE THREAD

**Issue by mo3mtr** [ElzeroWebSchool/Issue_Tracking#46]
الكود الموجود في الفيديو رقم 96 هو نفس الكود الموجود في الفيديو رقم 95 في كوري ال جافا سكريبت

**Comment by ElzeroWebSchool** [comment]
عملتها شكرا لك

**Comment by mo3mtr** [comment]
عفوا صديقي ومعلمي

في الأحد، ١ أكتوبر ٢٠٢٣, ٩:٢٣ م Elzero Web School ***@***.***>
كتب:
