### ISSUE TITLE
JavaScript Bootcamp | 96 - CSS Styling And Stylesheets

### ISSUE THREAD

**Issue by PhilopaterHany** [ElzeroWebSchool/Issue_Tracking#5]
الكود الموجود في الدرس دا هو هو بتاع الدرس القبلو

![image](https://user-images.githubusercontent.com/86812518/177267578-ba410ce0-64ee-4727-b539-fadbefe16cae.png)

**Comment by Yosof12** [comment]
صحيح، وأنا لاحظت

**Comment by ElzeroWebSchool** [comment]
بارك الله فيك صلحتها شكرا لك
