### ISSUE TITLE
Add a section back end 

### ISSUE THREAD

**Issue by Mahmoudhamdy12** [ElzeroWebSchool/Issue_Tracking#6]
![IMG_٢٠٢٢٠٧٠٥_١٥٤٨٤٧](https://user-images.githubusercontent.com/94189898/177343177-9dbf14b5-6d74-440c-9832-5eb74116df08.jpg)

 اضافة قسم back end للصفحة الرئيسية

**Comment by ElzeroWebSchool** [comment]
بارك الله فيك لسة بنعيد توزيع المسارات علشان في حاجات دجيدة اتضافت
